### ISSUE TITLE
can i use your title code-? and main menu? or do you wanna add it 

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SanicBTW/Fight-or-Flight-Port#1]
https://github.com/LEVIXDDLMAO/Sonic.EXE-2.5-3.0_SC

**Comment by MemeHoovy** [comment]
why can't you use the real source code?

**Comment by LEVIXDDLMAO** [comment]
Dude i told you already-

**Comment by MemeHoovy** [comment]
oh right...

**Comment by SanicBTW** [comment]
what

**Comment by SanicBTW** [comment]
> why can't you use the real source code?

its actually 10 times better tho, i only used the v2 source code title code and the main menu was my own code for a while, try adding the animation on the main menu tho

**Comment by LEVIXDDLMAO** [comment]
so should i use there code?

**Comment by SanicBTW** [comment]
yeah their code is a lot better than mine

**Comment by LEVIXDDLMAO** [comment]
kk :D Since the html build as you said on your port is on playable

**Comment by LEVIXDDLMAO** [comment]
unplayable*

**Comment by SanicBTW** [comment]
this port or the v2.5 html port

**Comment by LEVIXDDLMAO** [comment]
v2.5

**Comment by SanicBTW** [comment]
aa

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by SanicBTW** [comment]
i still have to work on the port tho, i currently have most of the stuff working except main menu, everything is laggy and freeplay menu seems to be working fine (tested it yesterday) but i cant really be sure if i will finish it soon

**Comment by LEVIXDDLMAO** [comment]
ah
